### ISSUE TITLE
library not compatible with Python 3.12

### ISSUE THREAD

**Issue by gregorleban** [prashnts/pybloomfiltermmap3#55]
Currently installing the library on Python 3.12 fails with errors like:

```
      src/pybloomfilter.c: In function ‘__Pyx_PyInt_As_int’:
      src/pybloomfilter.c:12917:53: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’
      12917 |             const digit* digits = ((PyLongObject*)x)->ob_digit;
            |                                                     ^~
      src/pybloomfilter.c:12972:53: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’
      12972 |             const digit* digits = ((PyLongObject*)x)->ob_digit;
            |                                                     ^~
```

other libraries had similar issues and seem to have solved them:

https://github.com/cython/cython/issues/5238

https://github.com/aio-libs/aiohttp/issues/7229

Can the same solution be applied here?

**Comment by cavoq** [comment]
I have the same issue with Python 3.13.0rc2

**Comment by cavoq** [comment]
Upgrading to the latest version of Cython and publishing again should resolve this issue. I was able to compile the library for python3.12.6 using Cython 3.0.11.

**Comment by gregorleban** [comment]
@cavoq : What do you mean by publishing again? I've installed the latest cython (3.0.12) and when I call

```
pip install pybloomfiltermmap3
```

I still get the exception:

```
src/pybloomfilter.c: In function ‘__Pyx_PyIndex_AsSsize_t’:
      src/pybloomfilter.c:14168:45: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’
      14168 |     const digit* digits = ((PyLongObject*)b)->ob_digit;
            |                                             ^~
      error: command '/usr/bin/gcc' failed with exit code 1
```

I'm running this on Python 3.13.0

**Comment by cavoq** [comment]
The package is compiled with an old version of cython. I already created a pull request which needs to be merged and published on pip to upgrade the dependencies.

**Comment by cavoq** [comment]
Since im not the owner there is not much i can do. I could publish a fork myself if there is enough demand.

**Comment by EmanuelaBoros** [comment]
@cavoq, please do :)

**Comment by cavoq** [comment]
I released my fork with updated dependencies and modernized the built for the PEP518 standard, the package is available under https://pypi.org/manage/project/pybloomfilter3/releases/. The fork is available under https://github.com/cavoq/pybloomfiltermmap3. It should work with the latest python versions.

**Comment by 123epsilon** [comment]
> I released my fork with updated dependencies and modernized the built for the PEP518 standard, the package is available under https://pypi.org/manage/project/pybloomfilter3/releases/. The fork is available under https://github.com/cavoq/pybloomfiltermmap3. It should work with the latest python versions.

Hi @cavoq - any idea why I'm getting this issue with your fork? I'm only having this problem in a CI: 

```
Collecting pybloomfilter3>=0.7.0 (from datasketch==1.6.5)
  Downloading pybloomfilter3-0.7.0.tar.gz (137 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [89 lines of output]
      Compiling src/pybloomfilter.pyx because it changed.
      [1/1] Cythonizing src/pybloomfilter.pyx
      configuration error: `project.license` must be valid exactly by one definition (2 matches found):
      
          - keys:
              'file': {type: string}
            required: ['file']
          - keys:
              'text': {type: string}
            required: ['text']
```

I believe that this is a [PEP 621](https://peps.python.org/pep-0621/#license) issue, maybe if we edit the `pyproject.toml` file to use the appropriate license format `license = {text = "MIT"}` this would work? I can submit a PR to your fork if you'd like.

**Comment by 123epsilon** [comment]
@cavoq I opened a PR, if you could review and merge it would be a big help: https://github.com/cavoq/pybloomfiltermmap3/pull/1

**Comment by cavoq** [comment]
Good catch! I will publish the new package later.

**Comment by idan3** [comment]
@cavoq Are there any breaking changes? Or I could simply replace `pybloomfiltermmap3==0.5.7` with `pybloomfilter3==0.7.1` and that's it. 
Also, are you planning on adding support for Python 3.13?

**Comment by cavoq** [comment]
@idan3 The API stays the same, so you should be able to just replace the current version with the latest version of pybloomfilter3. I tested it with 3.13.3, it should already be compatible.

**Comment by 123epsilon** [comment]
Hey @cavoq (sorry, I can't make issues on your fork) - does your repo require setuptools >= 80.9.0? The reason I ask is because that requirement is specified in pyproject.toml and requires python >= 3.9, whereas the repo README specifies that you can use python >= 3.5.

I ask because I'm working on https://github.com/ekzhu/datasketch/pull/246 and some of our CI tests need to run for users using version 3.7+.

**Comment by cavoq** [comment]
@123epsilon Hi, i enabled issues now. My fork is aimed to support newer versions of python, so i updated the latest version to 3.9+ now. If you need python 3.7, version 0.7.1 of my fork or the latest version of this repository should work.

**Comment by prashnts** [comment]
Hi @cavoq ! I'd missed the notifications, but I see you've published a fork. If you'd like to, we can merge back your changes here. I've just had someone reach out to me regarding a fix for deserialization bug which should be merged soon, as well. Happy to collaborate!

**Comment by prashnts** [comment]
I've pushed 0.6.1 (https://github.com/prashnts/pybloomfiltermmap3/releases/tag/v0.6.1) which should fix this issue. Also switched to pyproject style setup so correct version of cython should be automatically installed.
